CXXFLAGS= -I ~/kyopro -std=c++14 -Wall
SRCS=$(wildcard *.cpp)

a:a.cpp
	g++ $(CXXFLAGS) a.cpp
b:b.cpp
	g++ $(CXXFLAGS) b.cpp
c:c.cpp
	g++ $(CXXFLAGS) c.cpp
d:d.cpp
	g++ $(CXXFLAGS) d.cpp
e:e.cpp
	g++ $(CXXFLAGS) e.cpp
f:f.cpp
	g++ $(CXXFLAGS) f.cpp
g:g.cpp
	g++ $(CXXFLAGS) g.cpp

run: $(SRCS)
	./a.out
clean:
	rm ?
